[package]
name = "semver-hack-demo"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v2 = { git = "https://github.com/oli-obk/semver-hack-demo.git", branch = "v0.2.0", package = "semver-hack-demo" }
